server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/registration
  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
          format_sql: true
      show-sql: true